
JWT_SECRET_KEY = 'JWT_SECRETKEY'
SERVERURL = 'mongodb+srv://USERNAME:PASSSWORD@squaredtestcluster.g2hsl.mongodb.net'
ENCRYPT_KEY = 'ENCRYPT_KEY'
ENCRYPT_PHRASE = 'ENCRYPT_PHRASE'
DATABASENAME = 'SquaredDev'

